### PR TITLE
Fix email verification when `LOGIN_URL` is a url name.

### PR DESCRIPTION
**Pull request by maxpeterson**

### CODE REVIEW

**Comment by maxpeterson** [comment]
@incuna/backend please review / merge. I broke it!

**Comment by adam-thomas** [comment]
Does this still work when `LOGIN_URL` is a normal URL?

**Comment by maxpeterson** [comment]
@adam-thomas yes and there is a test for that

**Comment by adam-thomas** [comment]
:+1:

**Pull request merged**
