### PR TITLE
Connect user_logged_in signal

### PR DESCRIPTION
**Pull request by Ian-Foote**
Add to `TokenAuthentication.authenticate_credentials`.

### CODE REVIEW

**Comment by Ian-Foote** [comment]
@meshy @KevinEtienne Review?

**Comment by meshy** [comment]
:+1:

**Comment by meshy** [comment]
Looks good to me. Are there any other similar signals that we should be connecting?

**Comment by Ian-Foote** [comment]
Perhaps [`user_login_failed` and `user_logged_out`](https://github.com/django/django/blob/master/django/contrib/auth/signals.py).

**Comment by meshy** [comment]
:cool:

**Comment by Ian-Foote** [comment]
I think there's no good reason to connect `user_login_failed`. The `credentials` argument it [expects](https://github.com/django/django/blob/0f7f5bc9e7a94ab91c2b3db29ef7cf000eff593f/django/contrib/auth/__init__.py#L85-L86) is [cleaned](https://github.com/django/django/blob/0f7f5bc9e7a94ab91c2b3db29ef7cf000eff593f/django/contrib/auth/__init__.py#L41-L53) by django to avoid leaking sensitive information. But the only information we have to pass to `user_login_failed` is the `token`, which is sensitive.

**Comment by meshy** [comment]
Surely there would be no token on a login attempt, only an email and password?

**Comment by Ian-Foote** [comment]
Updated. I didn't need to add `user_login_failed`, because the [`authenticate`](https://github.com/django/django/blob/0f7f5bc9e7a94ab91c2b3db29ef7cf000eff593f/django/contrib/auth/__init__.py#L85-L86) function is called in [`AuthTokenSerializer.validate`](https://github.com/tomchristie/django-rest-framework/blob/67ae6b2552324ae25f31e71451ce6ff3cf2b79e4/rest_framework/authtoken/serializers.py#L16).

**Comment by meshy** [comment]
Looks good to me `:)` Happy when travis is

**Pull request merged**
