### PR TITLE
Remove patterns from urls

### PR DESCRIPTION
**Pull request by KevinEtienne**
`patterns` has been removed in 1.10
see https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10

### CODE REVIEW

**Comment by meshy** [comment]
\o/ Death to `patterns`! :+1:

**Comment by KevinEtienne** [comment]
I was surprised to find `patterns` in this library, as we've seem to remove a lot a long time ago :)

**Comment by meshy** [comment]
Yeah, it's been ages since I've seen it too... I guess it just managed to slip through the cracks somehow `:)`

**Comment by KevinEtienne** [comment]
Thanks :)

**Pull request merged**
