### PR TITLE
Allow user login after email verification providing a setting is true…

### PR DESCRIPTION
**Pull request by Minglee01**
@incuna/backend 

please review.

### CODE REVIEW

**Comment by wytrych** [comment]
No test?

**Comment by Minglee01** [comment]
I forgot adding one now

**Comment by Minglee01** [comment]
@incuna/backend 
bump
please review. travis is happy

**Comment by Minglee01** [comment]
@incuna/backend 

please review
Travis is happy

**Comment by adam-thomas** [comment]
Nice!

**Pull request merged**
