### PR TITLE
Improve new-password validation errors

### PR DESCRIPTION
**Pull request by adam-thomas**
Backporting in some fixes from later versions to v8.1.x.

@incuna/backend review please?

### CODE REVIEW

**Comment by adam-thomas** [comment]
Travis is totally broken right now:

```
py27-django16 runtests: commands[0] | coverage run ./user_management/tests/run.py
Coverage.py warning: No data was collected.
Traceback (most recent call last):
  File "./user_management/tests/run.py", line 7, in <module>
    from colour_runner.django_runner import ColourRunnerMixin
  File "/home/travis/build/incuna/django-user-management/.tox/py27-django16/lib/python2.7/site-packages/colour_runner/django_runner.py", line 1, in <module>
    from .runner import ColourTextTestRunner
  File "/home/travis/build/incuna/django-user-management/.tox/py27-django16/lib/python2.7/site-packages/colour_runner/runner.py", line 3, in <module>
    from .result import ColourTextTestResult
  File "/home/travis/build/incuna/django-user-management/.tox/py27-django16/lib/python2.7/site-packages/colour_runner/result.py", line 16, in <module>
    class ColourTextTestResult(result.TestResult):
  File "/home/travis/build/incuna/django-user-management/.tox/py27-django16/lib/python2.7/site-packages/colour_runner/result.py", line 28, in ColourTextTestResult
    _terminal = Terminal()
  File "/home/travis/build/incuna/django-user-management/.tox/py27-django16/lib/python2.7/site-packages/blessings/__init__.py", line 105, in __init__
    self._init_descriptor)
error: setupterm: could not find terminal
ERROR: InvocationError: '/home/travis/build/incuna/django-user-management/.tox/py27-django16/bin/coverage run ./user_management/tests/run.py'
___________________________________ summary ____________________________________
ERROR:   py27-django16: commands failed
The command "tox -e $TOX_ENV" exited with 1.
```

In the meantime, could I get some review? :P

**Comment by KevinEtienne** [comment]
I think the error is related to https://github.com/incuna/django-user-management/pull/138 looks like @Ian-Foote suggested a fix but we had another error.

**Comment by adam-thomas** [comment]
I have also seen `ValueError: I/O operation on closed file.` locally, I assumed it was something to do with my configuration.  I guess once Travis gets its stuff together we'll see that as well, in that case.  Any suggestions on what to do about either error?

**Comment by KevinEtienne** [comment]
I will try to not use a constant for [SIMPLE_PNG](https://github.com/incuna/django-user-management/blob/fdf0a62ac862819c000ba2563fcf8a33876483ef/user_management/api/avatar/tests/test_views.py#L33) for the second error. Or to find maybe if this behavior has been introduced with a new version of `PIL`.

**Comment by adam-thomas** [comment]
@KevinEtienne fixed the simple_png thing.

**Comment by adam-thomas** [comment]
@incuna/backend Travis is still failing.  It's the same insta-failure [as before](https://github.com/incuna/django-user-management/pull/141#issuecomment-144433032).  Any ideas? :/

**Comment by adam-thomas** [comment]
(The tests do pass locally, if people want to merge.)

**Comment by meshy** [comment]
It should be [reasonably easy](https://github.com/incuna/django-user-management/commit/1db465ac19868310a4a14fd177677ec74ce17e89) to fix the tests.

**Comment by adam-thomas** [comment]
How bizarre.  Thanks!

**Comment by meshy** [comment]
I know -- super weird.

**Comment by adam-thomas** [comment]
Er, wait.  I appear to already have that line in my `.travis.yml`.

**Comment by adam-thomas** [comment]
https://github.com/incuna/django-user-management/blob/serializer-validation/.travis.yml#L5

**Comment by meshy** [comment]
Ah.

Poop.

@incuna/backend (and @jturnbull) any ideas on how to fix the tests here?

**Comment by adam-thomas** [comment]
There is one other difference in @jturnbull's PR's `travis.yml`, so I've added it here.

**Comment by adam-thomas** [comment]
https://travis-ci.org/incuna/django-user-management/jobs/83073179#L138 OK we have actual errors now.  Apparently one of these changes doesn't work on Django 1.6. :(

**Comment by adam-thomas** [comment]
Woohoo, it works now!

**Comment by jturnbull** [comment]
Adam, once merged, can you merge this into #138 as one release please

**Comment by adam-thomas** [comment]
Sure!

**Comment by meshy** [comment]
Don't forget the changelog!

**Comment by adam-thomas** [comment]
Change is logged!

**Comment by meshy** [comment]
If you're merging this with #138, you ought to use the same version number it dictates

**Comment by adam-thomas** [comment]
I can do that when I merge it with #138 tbf?

**Comment by adam-thomas** [comment]
doesn't matter, did it anyway :)

**Comment by adam-thomas** [comment]
Bump?

**Comment by adam-thomas** [comment]
Continued, firmer bumpage.

**Comment by adam-thomas** [comment]
Thanks @jturnbull :)

**Comment by jturnbull** [comment]
Thanks adam, sorry for ignoring you :D

**Comment by adam-thomas** [comment]
hehehe, appreciated :P

**Pull request merged**
